"""blog/tools/gen-fonts.py — vendor the two brand faces so no visitor hits Google.

The site used to <link> straight to fonts.googleapis.com, which makes every
visitor's browser announce its IP to Google before the page paints. For a
Malaga-based site whose visitors are applying for nude shoots that is the wrong
default, and it was the ONLY third-party origin on the whole site — removing it
takes the count to zero.

Downloads the woff2 files Google serves for the exact weights the design system
uses, stores them under blog/assets/fonts/, and writes blog/assets/fonts.css
with the same @font-face rules pointing at local paths. Only the `latin` and
`latin-ext` subsets are kept: Spanish and English need nothing else, and the
cyrillic/vietnamese cuts would triple the payload for no reader.

Run when a weight is added to tokens.css, then commit the .woff2 files:

    python blog/tools/gen-fonts.py

Requires: Python 3. Network access to Google Fonts (a browser User-Agent is
mandatory -- Google serves .ttf to anything it doesn't recognise).
"""
import re
import sys
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT_DIR = REPO / "blog" / "assets" / "fonts"
OUT_CSS = REPO / "blog" / "assets" / "fonts.css"

# Exactly the weights the stylesheets ask for, and no more -- each unused weight
# is ~34 KB a visitor downloads to render nothing. Audited 2026-07-26:
#   Archivo (--font-body)  400 body text · 600 pills, buttons, badges, langtoggle
#   Cormorant (--font-head) 300 .step__n · 400 .display · 500 h3/tier · 400 italic deks
# The old <link> also requested Archivo 300 and 500; nothing has ever used them.
API = (
    "https://fonts.googleapis.com/css2"
    "?family=Archivo:wght@400;600"
    "&family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,400"
    "&display=swap"
)
# Google branches on User-Agent; a modern browser string is what yields woff2.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")
KEEP = {"latin", "latin-ext"}

HEADER = """/**
 * fonts.css — the brand faces, served from our own origin.
 *
 * GENERATED by blog/tools/gen-fonts.py -- do not edit by hand; re-run the tool.
 *
 * Self-hosted on purpose: linking fonts.googleapis.com sent every visitor's IP
 * to Google before first paint. These files are byte-identical to what Google
 * serves, minus the cyrillic/vietnamese subsets no reader of this site needs.
 */
"""


def fetch(url: str) -> bytes:
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA}), timeout=30).read()


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    css = fetch(API).decode("utf-8")

    # The API emits `/* subset */` immediately before each @font-face block.
    blocks = re.findall(r"/\* (\S+) \*/\s*(@font-face \{.*?\})", css, re.S)
    if not blocks:
        print("no @font-face blocks parsed -- did Google change the format?",
              file=sys.stderr)
        return 1

    rules, kept, skipped = [], 0, 0
    for subset, block in blocks:
        if subset not in KEEP:
            skipped += 1
            continue
        fam = re.search(r"font-family: '([^']+)'", block).group(1)
        weight = re.search(r"font-weight: (\d+)", block).group(1)
        style = re.search(r"font-style: (\w+)", block).group(1)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)

        slug = fam.lower().replace(" ", "-")
        name = f"{slug}-{weight}{'-italic' if style == 'italic' else ''}-{subset}.woff2"
        (OUT_DIR / name).write_bytes(fetch(url))
        kept += 1
        print(f"  {name:46s} {(OUT_DIR / name).stat().st_size // 1024:3d} KB")

        rules.append(block.replace(url, f"/blog/assets/fonts/{name}"))

    OUT_CSS.write_text(HEADER + "\n" + "\n".join(rules) + "\n", encoding="utf-8")
    total = sum(f.stat().st_size for f in OUT_DIR.glob("*.woff2")) // 1024
    print(f"\nwrote {OUT_CSS.relative_to(REPO)} -- {kept} faces, {total} KB "
          f"({skipped} non-latin subsets skipped)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
